version: "3"
services:

  database:
    image: mysql:5.7
    restart: always
    volumes:
      - database_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=registry
    expose:
      - 3306
    ports:
      - 9003:3306

  migration:
    image: arojunior/flyway:5.2.4
    command: "wait-for-it --timeout=30 --strict database:3306 -- \
        flyway \
          -url=jdbc:mysql://database:3306?useSSL=false \
          -schemas=registry \
          -user=root \
          -password=password \
          -connectRetries=60 migrate"
    volumes:
      - ./migration:/flyway/sql

volumes:
  database_data:
    driver: local
